### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jpgreth** [Fluiditype/fluiditype#2]
I miss a hint under which license this library is published. It would be great to read about it in [README.md](https://github.com/sboriskirov/fluiditype/blob/master/README.md)

**Comment by DanielRuf** [comment]
That would be very important.

**Comment by DanielRuf** [comment]
Best is: add a `LICENSE`file. See also https://choosealicense.com/

**Comment by boriskirov** [comment]
@jgreth @DanielRuf Thank you guys, I've just added it. The link you shared is super helpful due to it explains which license you may need. I will also add this here for documentation purposes, that GitHub actually provides the option once a new file is created to add the name **LICENSE** for it, which will give you the option to choose a template where everything is grouped and can be pushed quickly. Thank you for the comments, hope now it is better. I will also assume this as solved and close the issues, again I appreciate it.

**Comment by DanielRuf** [comment]
Hi @sboriskirov,

thanks for the quick response and that you have documented the license now =)

**Comment by jpgreth** [comment]
@sboriskirov thank you for this fast fix ;)
